2019-10-15 22:58:31,229 ERROR: Exception on /search [GET] [in d:\python3.6\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\python3.6\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python3.6\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python3.6\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python3.6\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\python3.6\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python3.6\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\python3.6\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "F:\python\flask_web 项目实战\app\main\routes.py", line 136, in search
    current_app.config['POSTS_PER_PAGE'])
  File "F:\python\flask_web 项目实战\app\models.py", line 15, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "F:\python\flask_web 项目实战\app\search.py", line 29, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "d:\python3.6\lib\site-packages\elasticsearch\client\utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "d:\python3.6\lib\site-packages\elasticsearch\client\__init__.py", line 805, in search
    "GET", _make_path(index, "_search"), params=params, body=body
  File "d:\python3.6\lib\site-packages\elasticsearch\transport.py", line 350, in perform_request
    timeout=timeout,
  File "d:\python3.6\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "d:\python3.6\lib\site-packages\elasticsearch\connection\base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2019-10-15 23:11:48,778 INFO: -----log startup-----> [in F:\python\flask_web 项目实战\app\__init__.py:78]
2019-10-15 23:12:01,804 ERROR: Exception on /search [GET] [in d:\python3.6\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\python3.6\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python3.6\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python3.6\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python3.6\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\python3.6\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python3.6\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\python3.6\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "F:\python\flask_web 项目实战\app\main\routes.py", line 136, in search
    current_app.config['POSTS_PER_PAGE'])
  File "F:\python\flask_web 项目实战\app\models.py", line 15, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
TypeError: 'NoneType' object is not iterable
2019-10-16 09:36:34,407 INFO: -----log startup-----> [in F:\python\flask_web 项目实战\app\__init__.py:78]
2019-10-16 09:49:42,820 INFO: -----log startup-----> [in F:\python\flask_web 项目实战\app\__init__.py:78]
2019-10-16 09:57:20,659 INFO: -----log startup-----> [in F:\python\flask_web 项目实战\app\__init__.py:78]
